#!/bin/bash
#
# chkconfig: 3 80 05
# description: Startup script for Glassfish

AS_JAVA=/opt/jdk1.8.0;
GLASSFISH_OWNER=codecheck;
GLASSFISH_HOME=/opt/glassfish4/glassfish;
export AS_JAVA GLASSFISH_HOME GLASSFISH_OWNER

start() {
    echo -n "Starting Glassfish: "
    iptables -t nat -A PREROUTING -p tcp -m tcp --dport 80 -j REDIRECT --to-ports 8080 
    iptables -t nat -A PREROUTING -p udp -m udp --dport 80 -j REDIRECT --to-ports 8080
    su $GLASSFISH_OWNER -c "$GLASSFISH_HOME/bin/asadmin start-domain"
    echo "done"
}

stop() {
    echo -n "Stopping Glassfish: "
    su $GLASSFISH_OWNER -c "$GLASSFISH_HOME/bin/asadmin stop-domain"
echo "done"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                stop
                start
                ;;
        *)
                echo $"Usage: Glassfish {start|stop|restart}"
                exit
esac
