#!/bin/bash

unzip $1
# rm $1

for f in *_*.* ; do
  studentWithNumbers=`expr match "$f" '\(.*_[0-9][0-9][0-9][0-9][0-9]*_[0-9][0-9][0-9][0-9][0-9]*_\)'`
  student=${studentWithNumbers%_*}
  student=${student%_*}
  file=${f:${#studentWithNumbers}}
  file=${file// /_}
  echo $student $file
  mkdir -p ${student}
  mv "$f" ${student}/${file}
done

