#!/bin/bash

# Splits D2L file name into student name, sortable date, file name without spaces
function d2ldate {
  case $1 in
  Jan) month=01 ;;
  Feb) month=02 ;;
  Mar) month=03 ;;
  Apr) month=04 ;;
  May) month=05 ;;
  Jun) month=06 ;;
  Jul) month=07 ;;
  Aug) month=08 ;;
  Sep) month=09 ;;
  Oct) month=10 ;;
  Nov) month=11 ;;
  Dec) month=12 ;;
  esac
  
  day=${2/,/}
  year=$3
  min=${4: -2}
  hour=${4:0:$((${#4} - 2))}
  if [ $hour == 12 ]; then hour=0 ; fi
  if [ $5 == PM ]; then hour=$(($hour + 12)) ; else hour=0$hour; hour=${hour: -2} ; fi
  date=${year}${month}${day}${hour}${min}
}

unzip $1
rm $1

for f in `ls *Download*.zip 2> /dev/null` ; do
  mv "$f" ${f// /_}
done

for f in *\ * ; do
  echo $f
  studentAndDate=`expr match "$f" '\(.* - .* [AP]M - \)'`
  studentAndDate=$studentAndDate
  student=${studentAndDate% - * - }
  datePart=${studentAndDate:${#student}}
  datePart=${datePart// - /}
  # D2L expands - in student name to " - "
  student=${student// - /-}
  student=${student// /_}
  student=${student##*_}_${student%_*}

  file=${f:${#studentAndDate}}
  file=${file// /_}

  d2ldate $datePart
  mkdir -p ${student}/${date}
  mv "$f" ${student}/${date}/${file}
done

rm index.html

for f in *_*/* ; do
  cd $f
    cp * ..
  cd ../..
done
  
