#!/bin/bash

# Already has student files in temp directory $2

BASEDIR=`dirname $0`

cd $2

CLASSPATH=`dirname $0`/codecheck.jar
if [ "${CLASSPATH/#\//}" == "$CLASSPATH" ] ; then CLASSPATH=`pwd`/"$CLASSPATH" ; fi

JAVA_HOME=/opt/jdk1.7.0

REPORT_JAR=`basename $3`.signed.zip
$JAVA_HOME/bin/jar cf $REPORT_JAR . 

LC_ALL=en_US.UTF-8 $JAVA_HOME/bin/java -Dcom.horstmann.codecheck -classpath $CLASSPATH com.horstmann.codecheck.Main $@ 

$JAVA_HOME/bin/jar uf $REPORT_JAR report.html 

MATCH=`grep --text -o '^[<]meta name="ID" content="\(.*\)"/>$' report.html`
if [[ -n $MATCH ]] ; then
  MATCH=${MATCH##*\=\"}
  ID=${MATCH%\"*}
  mv $REPORT_JAR $ID.signed.zip
  REPORT_JAR=$ID.signed.zip
fi

$JAVA_HOME/bin/jarsigner -keystore "$BASEDIR/horstmanncomodo.jks" -storepass rivu6nitt $REPORT_JAR  horstmanncomodo2013 
