#!/bin/bash

# Copyright 2006-2012 Cay S. Horstmann
#
# This file is part of Codecheck.
#
# Codecheck is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Codecheck is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Codecheck.  If not, see <http://www.gnu.org/licenses/>.

# To test a solution, run
# codecheck grade problemdir/solution problemdir 

# To grade student homework, run
# codecheck grade submissiondir problemdir

# Here, problemdir is the directory containing the directories
# named student and grader

# This script does not modify the contents of submissiondir unless
# the -s option is used

function grade {
    if [ "${SUBMISSIONDIR/#\//}" == "$SUBMISSIONDIR" ] ; then SUBMISSIONDIR="$STARTDIR"/"$SUBMISSIONDIR" ; fi

    if [ "${PROBLEMDIR/#\//}" == "$PROBLEMDIR" ] ; then PROBLEMDIR="$STARTDIR"/"$PROBLEMDIR" ; fi

    if [ "${WORKDIR/#\//}" == "$WORKDIR" ] ; then WORKDIR="$STARTDIR"/"$WORKDIR" ; fi

    cd "$SUBMISSIONDIR"
    REPORT_JAR=`basename $PROBLEMDIR`.signed.zip
    $JAVA_HOME/bin/jar cf $REPORT_JAR . 

    cd "$WORKDIR"

    if [ ! -z "$DEBUG" ] ; then
        echo LC_ALL=en_US.UTF-8 $JAVA_HOME/bin/java $JAVA_OPTS -Dcom.horstmann.codecheck -classpath $CLASSPATH com.horstmann.codecheck.Main $LEVEL "$SUBMISSIONDIR" "$PROBLEMDIR" $@
    fi
        
    LC_ALL=en_US.UTF-8 $JAVA_HOME/bin/java $JAVA_OPTS -Dcom.horstmann.codecheck -classpath $CLASSPATH com.horstmann.codecheck.Main $LEVEL "$SUBMISSIONDIR" "$PROBLEMDIR" $@

    cd "$SUBMISSIONDIR"

    if [ -e report.html ] ; then
        $JAVA_HOME/bin/jar uf $REPORT_JAR report.html
        MATCH=`grep --text -o '^[<]meta name="ID" content="\(.*\)"/>$' report.html`
        if [[ -n $MATCH ]] ; then
            MATCH=${MATCH##*\=\"}
            ID=${MATCH%\"*}
            mv $REPORT_JAR $ID.signed.zip
            REPORT_JAR=$ID.signed.zip
        fi
    fi

    $JAVA_HOME/bin/jarsigner -keystore "$BASEDIR/codecheck.jks" -storepass secret $REPORT_JAR codecheck > /dev/null
}

# Script start

STARTDIR=`pwd`
BASEDIR=`dirname $0`

# Pick up JAVA_HOME, maybe JAVA_OPTS

if [ -e $BASEDIR/codecheck.env ] ; then
    source $BASEDIR/codecheck.env
fi    

# Set classpath

if [ "${BASEDIR/#\//}" == "$BASEDIR" ] ; then BASEDIR="$STARTDIR"/"$BASEDIR" ; fi
CLASSPATH="$BASEDIR"/codecheck.jar:"$BASEDIR"/lib/\*

# Get server execution out of the way

if [ "$1" == "-s" ] ; then
    shift
    LEVEL=$1
    shift
    # Program is executed in submission dir
    SUBMISSIONDIR=$1
    WORKDIR=$1
    shift
    PROBLEMDIR=$1
    shift

    grade $@

    exit
fi

# From here on, client execution

# Detect Cygwin
cygwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true;
esac

linux=false
if [[ `uname` == 'Linux' ]]; then
   linux=true
fi

if [ -z "$BROWSER" ] ; then
  if $cygwin; then
    BROWSER=cygstart
  elif $linux; then
    BROWSER=xdg-open
  else
    BROWSER=open
  fi
fi

if [ "$1" == "-p" ] ; then BROWSER=cat ; shift ; fi

if [ "$1" == "-q" ] ; then BROWSER=echo ; shift ; fi

if [ "$1" == "-d" ] ; then DEBUG=true ; shift ; fi

if [ "$1" == "-t" ] ; then 
    BROWSER=cat 
    REPORT=report.txt 
    JAVA_OPTS="$JAVA_OPTS -Dcom.horstmann.codecheck.textreport"
    shift 
else
    REPORT=report.html
fi

if [ -z $2 ] ; then
  LEVEL=1
else
  LEVEL=$1
  shift
fi

if [ -z $2 ] ; then
  # Check solution
  PROBLEMDIR=$1
  SUBMISSIONDIR=`mktemp -d /tmp/codecheck.XXXXXXXXXX`

  if [ -e $PROBLEMDIR/solution ] ; then cp -R $PROBLEMDIR/solution/* $SUBMISSIONDIR ; fi
  case $LEVEL in 
    [1-9])
      for n in `seq 1 $LEVEL` ; do
        if [ -e $PROBLEMDIR/solution$n ] ; then cp -R $PROBLEMDIR/solution$n/* $SUBMISSIONDIR ; fi
      done
    ;;
    grade)
      for n in `seq 1 9` ; do
        if [ -e $PROBLEMDIR/solution$n ] ; then cp -R $PROBLEMDIR/solution$n/* $SUBMISSIONDIR ; fi
      done
      if [ -e $PROBLEMDIR/grader ] ; then cp -R $PROBLEMDIR/grader/* $SUBMISSIONDIR ; fi
    ;;
  esac  
  shift
else
  SUBMISSIONDIR=$1
  shift
  PROBLEMDIR=$1
  shift
fi

if [ -z "$LEVEL" ] || [ -z "$PROBLEMDIR" ] || [ ! -d "$SUBMISSIONDIR" ] || [ ! -d "$PROBLEMDIR" ]
then
    if [ -z "$LEVEL" ] ; then echo "No level supplied" ; fi
    if [ -z "$PROBLEMDIR" ] ; then echo "No problemdir supplied" ; fi
    if [ ! -d "$SUBMISSIONDIR" ] ; then echo "submissiondir $SUBMISSIONDIR doesn't exist" ; fi
    if [ ! -d "$PROBLEMDIR" ] ; then echo "problemdir $PROBLEMDIR doesn't exist" ; fi
    echo "Usage: `basename $0` [-pqst] level submissiondir problemdir"
fi

if $cygwin; then
    SUBMISSIONDIR=`cygpath -w $SUBMISSIONDIR`
    PROBLEMDIR=`cygpath -w $PROBLEMDIR`
    CLASSPATH=`cygpath -w $CLASSPATH`
fi

WORKDIR=`mktemp -d /tmp/codecheck.XXXXXXXXXX`

grade $@

$BROWSER "$SUBMISSIONDIR/$REPORT" 2> /dev/null 

# Checking student files
cd "$STARTDIR"
SUBMISSIONDIR=`mktemp -d /tmp/codecheck.XXXXXXXXXX`

if [ ! -z $SUBMISSIONDIR ] ; then
  # Checking student files
  if [ -e $PROBLEMDIR/student ] ; then 
    cd $PROBLEMDIR/student
    for f in `find .` ; do 
      if [ "$f" != "." ] ; then cp --parents $f $SUBMISSIONDIR ; fi
    done
    cd ../..
  fi
  case $LEVEL in 
    [1-9])
      for n in `seq 1 $LEVEL` ; do
        if [ -e $PROBLEMDIR/student$n ] ; then 
          cd $PROBLEMDIR/student$n
          for f in `find .` ; do 
            if [ "$f" != "." ] ; then cp --parents $f $SUBMISSIONDIR ; fi
          done
          cd ../..
        fi
      done
    ;;
    grade)
      for n in `seq 1 9` ; do
        if [ -e $PROBLEMDIR/student$n ] ; then 
          cd $PROBLEMDIR/student$n
          for f in `find .` ; do 
            if [ "$f" != "." ] ; then cp --parents $f $SUBMISSIONDIR ; fi
          done
          cd ../..
        fi
      done

      if [ -e $PROBLEMDIR/grader ] ; then 
          cd $PROBLEMDIR/grader
          for f in `find .` ; do 
              if [ "$f" != "." ] ; then cp --parents $f $SUBMISSIONDIR ; fi
          done
          cd ../..
      fi
    ;;
  esac

  if $cygwin; then
      SUBMISSIONDIR=`cygpath -w $SUBMISSIONDIR`
  fi
  WORKDIR=`mktemp -d /tmp/codecheck.XXXXXXXXXX`

  grade $@

  $BROWSER "$SUBMISSIONDIR/$REPORT" 2> /dev/null 
fi

  
