#!/bin/bash

# Copyright 2006-2012 Cay S. Horstmann
#
# This file is part of Codecheck.
#
# Codecheck is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Codecheck is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Codecheck.  If not, see <http://www.gnu.org/licenses/>.

# To test a solution, run
# codecheck grade problemdir/solution problemdir 

# To grade student homework, run
# codecheck grade submissiondir problemdir

# Here, problemdir is the directory containing the directories
# named student and grader

# This script does not modify the contents of submissiondir. 

# detect Cygwin
cygwin=false;
case "`uname`" in
  CYGWIN*) cygwin=true;
esac

linux=false
if [[ `uname` == 'Linux' ]]; then
   linux=true
fi

if [ -z "$BROWSER" ] ; then
  if $cygwin; then
    BROWSER=cygstart
  elif $linux; then
    BROWSER=xdg-open
  else
    BROWSER=open
  fi
fi

STARTDIR=`pwd`
BASEDIR=`dirname $0`
CLASSPATH="$BASEDIR/codecheck.jar"
if [ "${CLASSPATH/#\//}" == "$CLASSPATH" ] ; then CLASSPATH=`pwd`/"$CLASSPATH" ; fi

function usage() {
    echo "Usage: `basename $0` [-q] level submissiondir problemdir"
    exit
}

REPORT=report.html

if [ "$1" == "-p" ] ; then BROWSER=cat ; shift ; fi

if [ "$1" == "-q" ] ; then BROWSER=echo ; shift ; fi

if [ "$1" == "-t" ] ; then 
    BROWSER=cat 
    REPORT=report.txt 
    JAVA_OPTS=$JAVA_OPTS -Dcom.horstmann.codecheck.textreport
    shift 
fi

if [ -z $2 ] ; then
  LEVEL=1
else
  LEVEL=$1
  shift
fi

if [ -z $2 ] ; then
  # Checking solution
  PROBLEMDIR=$1
  SUBMISSIONDIR=`mktemp -d /tmp/codecheck.XXXXXXXXXX`
  # For checking student files
  SUBMISSIONDIR2=`mktemp -d /tmp/codecheck.XXXXXXXXXX`

  if [ -e $PROBLEMDIR/solution ] ; then cp -R $PROBLEMDIR/solution/* $SUBMISSIONDIR ; fi
  case $LEVEL in 
    [1-9])
      for n in `seq 1 $LEVEL` ; do
        if [ -e $PROBLEMDIR/solution$n ] ; then cp -R $PROBLEMDIR/solution$n/* $SUBMISSIONDIR ; fi
      done
    ;;
    grade)
      for n in `seq 1 9` ; do
        if [ -e $PROBLEMDIR/solution$n ] ; then cp -R $PROBLEMDIR/solution$n/* $SUBMISSIONDIR ; fi
      done
      if [ -e $PROBLEMDIR/grader ] ; then cp -R $PROBLEMDIR/grader/* $SUBMISSIONDIR ; fi
    ;;
  esac  
  shift
else
  SUBMISSIONDIR=$1
  shift
  PROBLEMDIR=$1
  shift
fi

if [ -z "$LEVEL" ] || [ -z "$PROBLEMDIR" ] || [ ! -d "$SUBMISSIONDIR" ] || [ ! -d "$PROBLEMDIR" ]
then
    echo $0 $@
    if [ -z "$LEVEL" ] ; then echo "No level supplied" ; fi
    if [ -z "$PROBLEMDIR" ] ; then echo "No problemdir supplied" ; fi
    if [ ! -d "$SUBMISSIONDIR" ] ; then echo "submissiondir $SUBMISSIONDIR doesn't exist" ; fi
    if [ ! -d "$PROBLEMDIR" ] ; then echo "problemdir $PROBLEMDIR doesn't exist" ; fi
    usage
fi

if [ "${SUBMISSIONDIR/#\//}" == "$SUBMISSIONDIR" ] ; then SUBMISSIONDIR=`pwd`/"$SUBMISSIONDIR" ; fi


if [ "${PROBLEMDIR/#\//}" == "$PROBLEMDIR" ] ; then PROBLEMDIR=`pwd`/"$PROBLEMDIR" ; fi

if $cygwin; then
    SUBMISSIONDIR=`cygpath -w $SUBMISSIONDIR`
    PROBLEMDIR=`cygpath -w $PROBLEMDIR`
    CLASSPATH=`cygpath -w $CLASSPATH`
fi

WORKDIR=`mktemp -d /tmp/codecheck.XXXXXXXXXX`

cd "$SUBMISSIONDIR"
REPORT_JAR=REPORT_JAR=`basename $PROBLEMDIR`.signed.zip
jar cf $REPORT_JAR .

cd "$WORKDIR"

JAVA_OPTS="$JAVA_OPTS -Dcom.horstmann.codecheck"

echo LC_ALL=en_US.UTF-8 java $JAVA_OPTS -classpath "$CLASSPATH" com.horstmann.codecheck.Main $LEVEL "$SUBMISSIONDIR" "$PROBLEMDIR" $@

LC_ALL=en_US.UTF-8 java $JAVA_OPTS -classpath "$CLASSPATH" com.horstmann.codecheck.Main $LEVEL "$SUBMISSIONDIR" "$PROBLEMDIR" $@
cd - > /dev/null
$BROWSER "$SUBMISSIONDIR/$REPORT" 2> /dev/null 
cd "$SUBMISSIONDIR"

if [ -e report.html ] ; then
  jar uf $REPORT_JAR report.html
  MATCH=`grep --text -o '^[<]meta name="ID" content="\(.*\)"/>$' report.html`
  if [[ -n $MATCH ]] ; then
    MATCH=${MATCH##*\=\"}
    ID=${MATCH%\"*}
    mv $REPORT_JAR $ID.signed.zip
    REPORT_JAR=$ID.signed.zip
  fi
fi

jarsigner -keystore "$BASEDIR/horstmanncomodo.jks" -storepass rivu6nitt $REPORT_JAR  horstmanncomodo > /dev/null

cd $STARTDIR

if [ ! -z $SUBMISSIONDIR2 ] ; then
  # Checking student files
  if [ -e $PROBLEMDIR/student ] ; then 
    cd $PROBLEMDIR/student
    for f in `find .` ; do 
      if [ "$f" != "." ] ; then cp --parents $f $SUBMISSIONDIR2 ; fi
    done
    cd ../..
  fi
  case $LEVEL in 
    [1-9])
      for n in `seq 1 $LEVEL` ; do
        if [ -e $PROBLEMDIR/student$n ] ; then 
          cd $PROBLEMDIR/student$n
          for f in `find .` ; do 
            if [ "$f" != "." ] ; then cp --parents $f $SUBMISSIONDIR2 ; fi
          done
          cd ../..
        fi
      done
    ;;
  esac  

  WORKDIR=`mktemp -d /tmp/codecheck.XXXXXXXXXX`

  cd "$WORKDIR"

  if $cygwin; then
      SUBMISSIONDIR2=`cygpath -w $SUBMISSIONDIR2`
  fi

  LC_ALL=en_US.UTF-8 java -Dcom.horstmann.codecheck $JAVA_OPTS -classpath "$CLASSPATH" com.horstmann.codecheck.Main $LEVEL "$SUBMISSIONDIR2" "$PROBLEMDIR" "$TITLE"
  cd - > /dev/null
  $BROWSER "$SUBMISSIONDIR2/$REPORT" 2> /dev/null 
fi

  
