#!/bin/bash

source `dirname $0`/codecheck.env

LANG=$1
shift

cd `dirname $1`

case _"$LANG" in
    _Python)        
        python3 -m py_compile $@
        ;;

    _Cpp)
        g++ -std=c++11 -g -o prog $@
        ;;

    _Scala)
        PATH=$PATH:$JAVA_HOME/bin $SCALA_HOME/bin/scalac $@
        ;;

    _Matlab)
        ;;

    _)  
        echo Unknown language $LANG 
        ;;          
esac
