#!/bin/bash

# (crontab -l ; echo "10 * * * * /opt/codecheck/killold") 2>&1 | sed "s/no crontab for $(whoami)//" | sort | uniq | crontab -

# Get all PIDs for process name
procs=`ps -ef | grep '\(codecheck\|runprog\)' | awk '{ print $2 }'`

# for each PID in PIDs array
for pid in $procs; do
    # get elapsed time in form mm:ss and remove ":" character
    # to make it easier to parse time 
    time=(`ps -o etime $pid | sed -e 's/[:-]/ /g'`)
    # get minutes from time
    min=${time[3]}
    # if proces runs 5 minutes then kill it
    if [ -n "$min" ] && [ "$min" -gt "5" ]; then
        kill -9 $pid
    fi
done;
