#!/bin/bash

# (crontab -l ; echo "*/10 * * * * /opt/codecheck/killold") 2>&1 | sed "s/no crontab for $(whoami)//" | sort | uniq | crontab -

# Get all PIDs for process name
procs=`ps -C codecheck,runprog,prog,racket -o pid=`

# for each PID 
for pid in $procs; do
    # get elapsed time in seconds
    sec=`ps --pid $pid -o etimes=`
     
    # if process runs 5 minutes then kill it
    if [ -n "$sec" ] && [ "$sec" -gt "300" ]; then
        systemd-cat -t killold echo Killing `ps --pid=$pid -o comm=` after $sec seconds
        kill -9 $pid
    fi
done;
