#!/bin/bash

# args: timeout interleaveio language module arg1 arg2 ...

# TODO: If nice isn't good enough, we can use cgroups. 
# sudo apt-get install cgroup-bin
# USER=ubuntu
# GROUP=ubuntu
# CGROUP=codecheck
# sudo cgcreate -a $USER:$GROUP -t $USER:$GROUP -g cpu:$CGROUP
# cgset -r cpu.shares=700 $CGROUP
# Then in this script, use 
# timeout ${TIMEOUT}s cgexec -g cpu:$CGROUP $PROG $@

# Why timeout and not just ulimit -t? timeout kills it after an elapsed
# time, and ulimit -t is probably redundant. If you just use ulimit -t,
# codecheck has stopped paying attention, and there is no use keeping the
# program alive.

CGROUP=codecheck

if [ -e `dirname $0`/codecheck.env ] ; then
    set -o allexport
    source `dirname $0`/codecheck.env
    set +o allexport
fi    

DIR=`dirname $0`
TIMEOUT=$1
shift
INTERLEAVEIO=$1
shift
LANG=$1
shift

case _"$LANG" in
  _Python)        
    ulimit -d 100000 -f 1000 -n 100 -v 100000 -t ${TIMEOUT}
    if [[ $1 =~ .*Test[0-9]*[.]py ]] ; then
        timeout ${TIMEOUT}s nice python3 -m unittest $@
    elif [[ $INTERLEAVEIO == 'true' ]] ; then
      TMPFILE=codecheck.XXXXXXXXXX
      while read line
      do
        echo "$line" >> $TMPFILE
      done
      cat $TMPFILE | nice $DIR/interleaveio.py ${TIMEOUT} python3 $@
      rm $TMPFILE
    else
      timeout ${TIMEOUT}s nice python3 $@
    fi
    ;;

  _C)
    ulimit -d 100000 -f 1000 -n 100 -v 100000 -t ${TIMEOUT}
    PROG=`dirname $1`/prog # Ignore module base name--we called it prog in comprog
    shift 
    timeout ${TIMEOUT}s nice $PROG $@
    ;;
  
  _Cpp)
    ulimit -d 100000 -f 1000 -n 100 -v 100000 -t ${TIMEOUT}
    PROG=`dirname $1`/prog # Ignore module base name--we called it prog in comprog
    shift
    if [[ $INTERLEAVEIO == 'true' ]] ; then
      nice $DIR/interleaveio.py ${TIMEOUT} $PROG $@
    else
      timeout ${TIMEOUT}s nice $PROG $@
    fi
    ;;

  _Scala)
    ulimit -d 100000 -f 1000 -n 100 -v 10000000 -t ${TIMEOUT}
    MODULE=`basename $1`
    CLASSPATH=`dirname $1`
    MODULE=${MODULE/.scala/}
    shift
    PATH=$PATH:$JAVA_HOME/bin timeout ${TIMEOUT}s nice $SCALA_HOME/bin/scala -classpath "$CLASSPATH" $MODULE $@
    ;;

  _Matlab)
    ulimit -d 10000 -f 1000 -n 100 -v 1000000 -t ${TIMEOUT}
    NO_AT_BRIDGE=1 nice octave --no-gui $@
    ;;

  _Racket)
    ulimit -d 100000 -f 1000 -n 100 -v 1000000 -t ${TIMEOUT}
    if grep -qE '\(define\s+\(\s*main\s+' $1 ; then
        timeout ${TIMEOUT}s nice racket -tm $@
    else
      timeout ${TIMEOUT}s nice racket -t $@
    fi 
    ;;

  _JavaScript)
    ulimit -d 1000000 -f 1000 -n 100 -v 10000000 -t ${TIMEOUT}
    timeout ${TIMEOUT}s nice node $@
    ;;

  _CSharp)
    ulimit -d 10000 -f 1000 -n 100 -v 100000 -t ${TIMEOUT}
    timeout ${TIMEOUT}s nice mono `dirname $1`/Prog.exe $@
    ;;

  _Haskell|_SML)
    ulimit -d 100000 -f 1000 -n 100 -v 1000000 -t ${TIMEOUT}
    PROG=`dirname $1`/prog
    shift
    timeout ${TIMEOUT}s nice $PROG $@
    ;;
  
  _)  
    echo Unknown language $LANG
    ;;          
esac

