#!/bin/bash

# args: language module arg1 arg2 ...

if [ -e `dirname $0`/codecheck.env ] ; then
    source `dirname $0`/codecheck.env
fi    

LANG=$1
shift

case _"$LANG" in
    _Python)        
        ulimit -d 1000 -f 1000 -n 100 -v 100000
        python3 $@
        ;;

    _Cpp)
        ulimit -d 1000 -f 1000 -n 100 -v 100000
        PROG=`dirname $1`/prog # Ignore module base name--we called it prog in comprog
        shift 
        $PROG $@
        ;;

    _Scala)
        ulimit -d 1000 -f 1000 -n 100
        MODULE=`basename $1`
        MODULE=${MODULE/.scala/}
        shift
        PATH=$PATH:$JAVA_HOME/bin $SCALA_HOME/bin/scala $MODULE $@
        ;;

    _)  
        echo Unknown language $LANG
        ;;          
esac

